import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Provider from "./Provider";
import NavBar from "@/Components/NavBar";
import SearchBox from "@/Components/SearchBox";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        <Header />
        <NavBar />
        <SearchBox  />
        {children}
        </Provider>
        </body>
    </html>
  );
}
